// Writes css/tokens.css from src/tokens/palette.json and src/tokens/roles.json.
// With --check, compares a fresh generation with the committed file instead.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

/** @param {string} path */
const fromRoot = (path) =>
  fileURLToPath(new URL(`../${path}`, import.meta.url));
/**
 * @param {string} path
 * @returns {Record<string, any>}
 */
const readJson = (path) => JSON.parse(readFileSync(fromRoot(path), 'utf8'));
/** @param {string} name */
const kebab = (name) => name.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`);

/** @type {Record<string, string>} */
const palette = readJson('src/tokens/palette.json');
/** @type {{ light: Record<string, string>, dark: Record<string, string> }} */
const roles = /** @type {any} */ (readJson('src/tokens/roles.json'));

/**
 * @param {Record<string, string>} assignments
 * @param {string} indent
 */
function roleLines(assignments, indent) {
  return Object.entries(assignments).map(([role, primitive]) => {
    if (!(primitive in palette)) {
      throw new Error(`role ${role} names unknown primitive ${primitive}`);
    }
    return `${indent}--${kebab(role)}: var(--${kebab(primitive)});`;
  });
}

if (
  Object.keys(roles.light).join() !== Object.keys(roles.dark).join() ||
  Object.keys(roles.light).length === 0
) {
  throw new Error(
    'light and dark must assign the same roles in the same order',
  );
}

const css = [
  '/* Generated by scripts/generate-tokens.mjs. Do not edit by hand. */',
  ':root {',
  ...Object.entries(palette).map(
    ([name, hex]) => `  --${kebab(name)}: ${hex};`,
  ),
  ...roleLines(roles.light, '  '),
  '  color: var(--on-surface);',
  '  background: var(--surface);',
  '  font-family: system-ui, sans-serif;',
  '}',
  ":root[data-theme='dark'] {",
  ...roleLines(roles.dark, '  '),
  '}',
  '@media (prefers-color-scheme: dark) {',
  "  :root[data-theme='system'] {",
  ...roleLines(roles.dark, '    '),
  '  }',
  '}',
  '',
].join('\n');

const target = fromRoot('css/tokens.css');
if (process.argv.includes('--check')) {
  let committed = '';
  try {
    committed = readFileSync(target, 'utf8');
  } catch {
    // A missing file is reported as stale below.
  }
  if (committed !== css) {
    console.error('css/tokens.css is stale. Run: npm run generate:tokens');
    process.exit(1);
  }
} else {
  writeFileSync(target, css);
}
